/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bbUsdFaucetSol from "./bbUSDFaucet.sol";
export type { bbUsdFaucetSol };
import type * as mock from "./mock";
export type { mock };
export type { ERC1155Receiver } from "./ERC1155Receiver";
export type { BbFix } from "./BbFix";
export type { BbFixPool } from "./BbFixPool";
export type { BbUSD } from "./BbUSD";
