/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bbUsdSol from "./bbUSD.sol";
export type { bbUsdSol };
import type * as bbUsdFaucetSol from "./bbUSDFaucet.sol";
export type { bbUsdFaucetSol };
import type * as mock from "./mock";
export type { mock };
export type { Lock } from "./Lock";
export type { BbFix } from "./BbFix";
export type { BbFixICO } from "./BbFixICO";
