/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155ReceiverMock__factory } from "./ERC1155ReceiverMock__factory";
export { BbFixMock__factory } from "./BbFixMock__factory";
