/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155ReceiverMock } from "./ERC1155ReceiverMock";
export type { BbFixMock } from "./BbFixMock";
